spring: 
  profiles: 
    active: 
    - dev

---     
spring: 
  profiles: dev   #开发环境
  application: 
      name: microsvccloud-config-gh-dev
      
---     
spring: 
  profiles: test   #测试环境
  application: 
      name: microsvccloud-config-gh-test-1
